module.exports = {
  DAI_CAT: [
    "Ngôi sao may mắn đang chiếu rọi bản mệnh của bạn. Một niềm vui vô cùng ý nghĩa sẽ xuất hiện vào cuối ngày. Hãy mở rộng tấm lòng để đón nhận.",
    "Đường công danh học vấn hôm nay vô cùng xán lạn. Mọi sự khởi đầu mới đều gặp thuận lợi, những khúc mắc cũ sẽ tự động được hóa giải.",
    "Vận đào hoa đang nở rộ rực rỡ xung quanh bạn. Sự duyên dáng tự nhiên toát ra từ bạn sẽ thu hút ánh nhìn thiện cảm từ những người xung quanh.",
    "Hôm nay ra cửa dễ gặp quý nhân phù trợ. Mọi khó khăn, trắc trở đều sẽ có người đưa tay tương trợ kịp thời, giúp vạn sự hanh thông.",
    "Năng lượng vũ trụ đang hoàn toàn ủng hộ bạn. Một dự định ấp ủ từ lâu đã đến lúc chín muồi, hãy mạnh dạn nắm bắt cơ hội vàng này.",
    "Hôm nay là một ngày đại cát. Nguồn sinh khí dồi dào giúp tâm trí bạn vô cùng minh mẫn, đưa ra được những quyết định sáng suốt mang tính bước ngoặt.",
    "Gia đạo bình an, các mối quan hệ hòa hợp. Sự thấu hiểu và sẻ chia sẽ làm sâu đậm thêm những sợi dây liên kết xung quanh bạn.",
    "Vượng khí hội tụ mang lại nhiều phước lành. Bất kể bạn làm việc gì hôm nay cũng đều trơn tru, dễ dàng đạt được thành quả như ý.",
    "Sức hút cá nhân của bạn hôm nay vô cùng mãnh liệt. Lời nói mang đầy tính thuyết phục, thích hợp để hóa giải những hiểu lầm từ quá khứ.",
    "Bầu trời vận mệnh quang đãng không một gợn mây. Những hạt giống nỗ lực bạn gieo trồng bấy lâu nay chuẩn bị đơm hoa kết trái rực rỡ.",
    "Một tin tức tốt lành bất ngờ từ phương xa đang trên đường tìm đến bạn. Mọi sự chờ đợi kiên nhẫn đều sẽ được đền đáp xứng đáng.",
    "Hôm nay là thời điểm lý tưởng để kết nối và mở rộng các mối quan hệ. Một cơ hội lớn có thể mở ra từ những cuộc gặp gỡ tình cờ.",
    "Trực giác của bạn hôm nay vô cùng nhạy bén. Hãy lắng nghe tiếng nói từ sâu thẳm bên trong, nó sẽ dẫn đường chỉ lối cho bạn đi đến vinh quang.",
    "Cát tinh phù trợ, vạn sự cát tường. Một cuộc hội ngộ bất ngờ sẽ mang đến cho bạn những kỷ niệm đẹp đẽ và ấm áp khó quên.",
    "Thời vận đang lên, bạn làm việc gì cũng như được trải thảm đỏ. Hãy tự tin sải bước và khẳng định giá trị bản thân.",
    "Một ngày đại thắng lợi trên mọi mặt trận. Sự tự tin tuyệt đối giúp bạn làm chủ mọi tình huống và thu về kết quả mỹ mãn."
  ],
  TIEU_CAT: [
    "Đường tài lộc có dấu hiệu khởi sắc nhẹ nhàng. Dù không phải sự thay đổi lớn nhưng cũng đủ mang lại cho bạn cảm giác an tâm và dư dả.",
    "Năng lượng chữa lành đang bao trùm lấy bạn. Những tổn thương hay muộn phiền cũ sẽ dần được xoa dịu, trả lại sự an yên trong tâm hồn.",
    "Tâm an thì vạn sự an. Hôm nay sự tĩnh lặng trong tâm trí sẽ giúp bạn vượt qua mọi cám dỗ, giữ vững được lập trường và tỏa sáng.",
    "Sự nhẫn nại của bạn cuối cùng cũng đơm hoa. Người khác bắt đầu nhận ra và đánh giá cao những phẩm chất tốt đẹp ẩn sâu bên trong bạn.",
    "Ngày hôm nay đánh dấu một sự chuyển mình tích cực. Bạn sẽ tìm thấy nguồn cảm hứng mới mẻ để hoàn thành nốt những dự định còn dang dở.",
    "Một ý tưởng sáng tạo đột phá sẽ lóe lên trong đầu bạn. Đừng bỏ lỡ nó, vì đây có thể là chiếc chìa khóa mở ra cánh cửa thành công.",
    "Khúc mắc trong một mối quan hệ quan trọng sẽ tự động được gỡ bỏ. Hai tâm hồn thấu hiểu và xích lại gần nhau hơn, phá vỡ mọi rào cản.",
    "Bạn mang trong mình nguồn sinh khí dồi dào, lan tỏa năng lượng lạc quan đến tất cả những người mà bạn tiếp xúc ngày hôm nay.",
    "Vũ trụ đang gửi đến một tín hiệu đáng mừng cho những nỗ lực thầm lặng của bạn. Hãy tiếp tục tiến bước, phía trước là ánh sáng.",
    "Sự lương thiện của bạn luôn mang lại phước báu. Một người bạn từng giúp đỡ có thể mang đến một sự báo đáp bất ngờ và vô cùng ý nghĩa.",
    "Sự tinh tế trong cách ứng xử giúp bạn ghi điểm tuyệt đối trong mắt một người quan trọng. Các mối quan hệ bước sang một trang mới tốt đẹp hơn.",
    "Nhịp sinh học đang ở đỉnh cao, cơ thể tràn đầy sinh lực. Hãy dùng năng lượng này để tạo ra những giá trị tốt đẹp cho bản thân.",
    "Mọi hiểu lầm sẽ được hóa giải, nhường chỗ cho sự tin tưởng. Hôm nay là ngày của sự gắn kết và những lời nói chân thành.",
    "Một người lớn tuổi hoặc bề trên sẽ mang đến cho bạn lời khuyên vô giá. Hãy biết ơn và ghi nhớ, nó sẽ giúp ích rất nhiều cho tương lai.",
    "Cảm giác thăng hoa trong tâm hồn sẽ đi theo bạn suốt cả ngày. Bầu không khí xung quanh dường như cũng trở nên thanh lọc và nhẹ nhàng hơn.",
    "Sự minh mẫn giúp bạn nhìn thấu mọi vấn đề. Hôm nay là ngày để bạn tỏa sáng bằng trí tuệ và sự điềm đạm của chính mình."
  ],
  BINH_HOA: [
    "Hôm nay là một ngày bình lặng, dòng chảy năng lượng trôi qua êm ả. Không có quá nhiều biến động, rất thích hợp để bạn thư giãn tâm trí.",
    "Mọi việc đang diễn ra theo đúng quỹ đạo tự nhiên. Đôi khi không cần phải gắng sức thay đổi cục diện, cứ thuận theo tự nhiên là tốt nhất.",
    "Bạn đang đi đúng hướng, nhưng quả ngọt cần thêm chút thời gian để đơm bông. Kiên nhẫn là bài học lớn nhất mà vận mệnh gửi đến bạn hôm nay.",
    "Tâm trí cần được nghỉ ngơi. Đừng nhồi nhét quá nhiều lo âu. Một chút tĩnh lặng sẽ giúp bạn tìm lại sự cân bằng vốn có.",
    "Một ngày không tốt cũng không xấu. Mọi thứ duy trì ở mức ổn định. Hãy tận hưởng sự bình yên hiếm hoi này giữa những bộn bề cuộc sống.",
    "Hãy chậm lại một nhịp, quan sát nhiều hơn là phán xét. Sự điềm tĩnh sẽ giúp bạn nhìn nhận vấn đề một cách khách quan và sâu sắc hơn.",
    "Có những việc dang dở cần bạn kiên nhẫn hoàn thiện. Sự tỉ mỉ trong ngày hôm nay sẽ mang lại kết quả chắc chắn về sau.",
    "Nếu cảm thấy cạn kiệt năng lượng, hãy tự cho phép bản thân được nghỉ ngơi. Khôi phục sinh lực quan trọng hơn việc cố gắng mù quáng.",
    "Đừng cố kiểm soát những thứ ngoài tầm với. Việc chấp nhận thực tại sẽ giúp bạn vơi đi rất nhiều muộn phiền không đáng có.",
    "Hôm nay là thời điểm lý tưởng để quay về bên trong. Việc thấu hiểu bản thân sẽ mang lại sức mạnh lớn hơn bất kỳ sự công nhận nào từ bên ngoài.",
    "Dù ai nói ngả nói nghiêng, bạn hãy cứ giữ vững lập trường của mình. Sự kiên định là chìa khóa duy trì sự ổn định trong ngày hôm nay.",
    "Sẽ có một chút xáo trộn nhỏ, nhưng nó không ảnh hưởng đến đại cục. Khả năng thích ứng linh hoạt sẽ giúp bạn vượt qua dễ dàng.",
    "Một cử chỉ tử tế từ bạn có thể thay đổi ngày mới của ai đó. Dù chỉ là một nụ cười, cũng đủ để xua tan đi năng lượng u ám.",
    "Đôi khi lùi lại một bước là để nhìn rõ toàn cảnh bức tranh vận mệnh. Hãy giữ khoảng cách an toàn với những rắc rối không cần thiết.",
    "Dĩ hòa vi quý là phương châm sống của hôm nay. Sự mềm mỏng và khéo léo sẽ giúp bạn tránh được những va chạm không đáng có.",
    "Hãy cho mình ít phút ngắt kết nối với thế giới ồn ào. Sự tĩnh tâm là phương thuốc tốt nhất cho một tâm hồn đang xáo động."
  ],
  TIEU_HUNG: [
    "Bản mệnh hôm nay có chút xáo động, cảm xúc dễ trở nên thất thường. Khuyên bạn nên hít thở sâu, giữ cái đầu lạnh trước khi ra quyết định.",
    "Nguồn sinh khí đang có dấu hiệu suy giảm. Cơ thể đang lên tiếng đòi hỏi được nghỉ ngơi. Đừng vắt kiệt sức lực của mình vì những thứ vô bổ.",
    "Đường tài lộc hôm nay khá mù mịt. Nguy cơ hao tài tốn của tiềm ẩn xung quanh. Tuyệt đối tránh những quyết định liên quan đến vay mượn.",
    "Có điềm báo về sự đố kỵ và ganh ghét từ những người xung quanh. Hãy khiêm nhường, thu mình lại một chút để tránh thu hút sự chú ý tiêu cực.",
    "Một sự cố giao tiếp có thể châm ngòi cho những rạn nứt không đáng có. Hãy luôn giữ thái độ hòa nhã và giải thích mọi chuyện thật cặn kẽ.",
    "Điềm báo thất lạc tài sản hoặc đánh rơi đồ vật quan trọng. Khi ra ngoài hoặc ở nơi đông người, hãy kiểm tra kỹ càng hành trang của mình.",
    "Kỳ vọng càng nhiều, thất vọng càng sâu. Hôm nay đừng đặt quá nhiều niềm tin vào lời hứa của người khác, hãy tự dựa vào chính sức mình.",
    "Những dự định quan trọng có thể gặp phải trở ngại khách quan và buộc phải trì hoãn. Đừng nôn nóng, hãy chuẩn bị sẵn một phương án dự phòng an toàn.",
    "Cẩn trọng khi xuất hành hoặc di chuyển. Hôm nay không phải là ngày tốt để vội vã. Đi chậm lại, nhìn trước ngó sau để đảm bảo sự bình an.",
    "Sự lơ đãng có thể khiến bạn vấp phải những sai lầm sơ đẳng. Làm việc gì hôm nay cũng cần sự tập trung cao độ và kiểm tra lại nhiều lần.",
    "Đừng để bị lóa mắt bởi những cám dỗ hay lời hứa hẹn ngọt ngào. Không có cái bẫy nào được giăng ra mà không có mồi nhử, hãy thật tỉnh táo.",
    "Tuyệt đối tránh việc đứng ra bảo lãnh hay gánh vác trách nhiệm thay cho người khác. Sự nể nang của bạn hôm nay sẽ phải trả giá đắt.",
    "Sẽ có người cố tình khiêu khích để làm suy yếu lý trí của bạn. Nhớ kỹ: người nổi giận là người thua cuộc. Sự im lặng phớt lờ là đòn đáp trả mạnh nhất.",
    "Vạn sự khởi đầu nan, hôm nay làm việc gì cũng cảm thấy có chút cản trở. Khuyên bạn nên lùi lại một bước, chỉ tập trung vào việc quen thuộc.",
    "Bao đồng chuyện thiên hạ chỉ khiến bạn chuốc lấy phiền phức. Việc của ai người nấy lo, hôm nay tuyệt đối không xen vào chuyện không phải của mình.",
    "Một ngày bị bao phủ bởi luồng sinh khí u ám, cảm giác chông chênh dễ ùa về. Hãy cho phép mình được nghỉ ngơi, ngày mai bình minh sẽ lại tới."
  ],
  DAI_HUNG: [
    "Đề phòng thị phi bủa vây tứ phía. Hôm nay nên áp dụng triết lý 'im lặng là vàng', cẩn trọng tuyệt đối trong từng lời ăn tiếng nói kẻo rước họa vào thân.",
    "Áp lực đang đè nặng lên đôi vai khiến bạn cảm thấy ngột ngạt và kiệt sức. Đừng cố chấp gồng gánh một mình, hãy buông bỏ bớt những trách nhiệm không cần thiết.",
    "Sóng gió có thể ập đến bất ngờ, thử thách tận cùng bản lĩnh của bạn. Giữ vững sự điềm tĩnh và lý trí chính là chiếc phao cứu sinh duy nhất lúc này.",
    "Một ngày đại kỵ cho mọi hình thức tranh cãi hay đôi co. Dù bạn nắm phần đúng, sự dính líu cũng chỉ mang lại sự hao tổn tâm trí nghiêm trọng.",
    "Sự nông nổi trong phút chốc có thể dẫn đến những quyết định sai lầm không thể cứu vãn. Cần phải kiểm soát chặt chẽ những cơn bốc đồng từ nội tâm.",
    "Mối quan hệ vô cùng quan trọng đang đối mặt với bờ vực rạn nứt lớn. Tuyệt đối không được buông ra những lời nói sắc nhọn làm tổn thương sâu sắc đối phương.",
    "Những rắc rối bất ngờ liên tục phát sinh gây gián đoạn hoàn toàn kế hoạch của bạn. Đừng cố gắng chống cự, hãy lui về phòng thủ và chờ đợi sóng gió qua đi.",
    "Sức chịu đựng của bạn sẽ bị đẩy đến giới hạn cuối cùng bởi những sự việc hoàn toàn trái ý. Hãy lập tức tách mình ra khỏi môi trường độc hại để tự xoa dịu.",
    "Hư vinh là liều thuốc độc chí mạng. Đừng vì thể diện mà nhận lời làm những việc vượt quá sức mình, hậu quả để lại sẽ phá hủy hoàn toàn niềm tin từ người khác.",
    "Sự vội vàng và hấp tấp có thể khiến bạn gây ra một hậu quả cực kỳ nghiêm trọng. Hãy đóng băng mọi hành động quan trọng và chờ đến một ngày khác sáng sủa hơn.",
    "Đố kỵ là ngọn lửa thiêu rụi chính bản thân bạn từ bên trong. Năng lượng xung khắc dâng cao dễ khiến bạn đánh mất lý trí và làm ra những chuyện đáng ân hận.",
    "Hôm nay tuyệt đối không phải là thời điểm để bày tỏ tình cảm hay mong cầu bất kỳ sự hàn gắn nào. Mọi nỗ lực cưỡng cầu đều sẽ nhận lại một cái kết phũ phàng.",
    "Ngủ quên trên chiến thắng là con đường ngắn nhất dẫn đến sự sụp đổ. Sự chủ quan của bạn hôm nay sẽ tạo cơ hội vàng cho đối thủ tung đòn chí mạng.",
    "Sự bảo thủ và cái tôi quá lớn sẽ che mờ hoàn toàn đôi mắt của bạn. Từ chối lắng nghe lời khuyên răn sẽ đẩy bạn thẳng vào những cái bẫy đã được giăng sẵn.",
    "Một sự mất mát nhỏ có thể xảy ra, cả về vật chất lẫn tinh thần. Đừng cố bấu víu vào những thứ không còn thuộc về mình, hãy học cách buông tay để bảo toàn sinh khí."
  ]
};
