services:
  - type: web
    name: quan-ly-lop
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
